CREATE TABLE CLIENTE (
    IDCLIENTE INT AUTO_INCREMENT  PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD1 VARCHAR(16) NOT NULL
);


CREATE TABLE CONTA (
    IDCONTA INT AUTO_INCREMENT  PRIMARY KEY,
    NUMERODACONTA INT NOT NULL,
	TIPODECONTA VARCHAR(2) NOT NULL,
    SALDOCONTA DECIMAL NOT NULL,
    IDCLIENTE INT NULL,
    FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE) 
	/*CONSTRAINT CONTA_FK FOREIGN KEY(ID) REFERENCES CLIENTE(ID)*/
);

CREATE TABLE TRANSACOES (
	IDTRANSACAO INT AUTO_INCREMENT  PRIMARY KEY,
	CONTAORIGEM INT NOT NULL,
	CONTADESTINO INT NOT NULL,
	VALORTRANSACAO DECIMAL NOT NULL, 
	DATATRANSACAO DATETIME,
	IDCONTA INT NULL,
	FOREIGN KEY (IDCONTA) REFERENCES CONTA(IDCONTA)
)