CREATE TABLE CLIENTE (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD1 VARCHAR(16) NOT NULL
);

/*CREATE TABLE TIPODECONTA (
    IDTIPOCONTA INT AUTO_INCREMENT  PRIMARY KEY,
    TIPODECONTA ENUM ('CC', 'CP')    
);
*/
CREATE TABLE CONTA (
    IDCONTA INT AUTO_INCREMENT  PRIMARY KEY,
    NUMERODACONTA INT NOT NULL,
  --  TIPODECONTA VARCHAR(2) NOT NULL,
    SALDOCONTA DECIMAL NOT NULL,
    ID INT NOT NULL,
    FOREIGN KEY(ID) REFERENCES CLIENTE(ID) 
	/*CONSTRAINT CONTA_FK FOREIGN KEY(ID) REFERENCES CLIENTE(ID)*/
);